spring: 
    datasource: 
        name: test
        url: jdbc:mysql://localhost:3306/raisehot
        username: raisehot
        password: raisehot
        #使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:  
    mapperLocations: classpath:conf/mapper/*.xml
    typeAliasesPackage: com.hottop.raisehot.model
    #configLocations: classpath:conf/mybatis-config.xml
server:
    port: 8080
    session:
      timeout: 30
    address: 127.0.0.1
    contextPath: /raisehot
    tomcat:
        protocolHeader: x-forwarded-proto
        remoteIpHeader: x-forwarded-for
        basedir:
        backgroundProcessorDelay: 30 # secs  
#debug: true 
logging:
  config: classpath:conf/logback-spring.xml     